### PR TITLE
Brute Force Scene

### PR DESCRIPTION
**Pull request by jesi-rgb**
# Brute Force scene
Scene presenting why brute forcing the TSP problem is really not a good idea.

# Video clip

https://user-images.githubusercontent.com/50735312/173347516-1731d40c-3517-4f1a-a1d2-9ba3592a80ad.mp4

### CODE REVIEW

**Comment by jesi-rgb** [comment]
@nipunramk smash this animation with feedback!

**Comment by nipunramk** [comment]
@jesi-rgb overall, amazing work here!
Couple of small additions
At 1:04 -- have some indication/written reference to (n - 1)! in the script. And then at 1:09, with that information, show the correct version of (n - 1)! / 2
Also at 1:17, just so you know my personal preference, I prefer that there be no frames with just numbers/text in them when some visual can exist. I suggest adding a 20 city TSP graph to the last frame (and if it looks good, show the complete graph version of it). We can put the number at the bottom of the frame with the graph.

**Comment by jesi-rgb** [comment]
Feedback applied! Lemme know your thoughts! @nipunramk 

https://user-images.githubusercontent.com/50735312/173893182-d1a04236-1d2a-45b0-826e-7620a51c8e93.mp4

**Comment by nipunramk** [comment]
@jesi-rgb love the additions. Final piece of feedback:

The edges on the graph at 1:28 look fantastic, but I feel the vertices are too big? Could we scale down the vertices a bit?

A problem you will probably encounter is that the edges will overlap the node after scaling down. I added some functionality to the TSPGraph class where you can pass a buff into get_all_edges.

In your use case you can do the following:

`complete_graph = TSPGraph(range(20), ...)`
`# scale the vertices afterwards`
`all_edges = complete_graph.get_all_edges(buff=complete_graph.vertices[0].width / 2)`

**Comment by jesi-rgb** [comment]
oh thats cool! nice. i left it like that because this is not implementing the functionality that makes all the nodes the same. 

whenever you merge, that will apply. but your functionality is also very cool!

**Comment by jesi-rgb** [comment]
@nipunramk some cool changes that this PR brings apart from the scene include:

- The ability to pass in a custom arrow to create edges with that arrow in `get_all_edges` and `create_edge`
	- https://github.com/jesi-rgb/Video-Dev/blob/bb7dd27bc5f58857b5e013117e2b6ca7998b97c4/TSPProblem/solving_tsp.py#L79
- The ability to specify the maximum number of combinations and also return duplicates for some scenes that I needed in `get_all_tour_permutations`
	- https://github.com/jesi-rgb/Video-Dev/blob/bb7dd27bc5f58857b5e013117e2b6ca7998b97c4/TSPProblem/solver_utils.py#L6
- Fix a bug with `get_cost_from_permutation`
	- https://github.com/jesi-rgb/Video-Dev/blob/bb7dd27bc5f58857b5e013117e2b6ca7998b97c4/TSPProblem/solver_utils.py#L70

**Pull request merged**
