### PR TITLE
RED-30: `BruteForceMethod` animation

### PR DESCRIPTION
**Pull request by jesi-rgb**
## Problem
`BruteForceMethod` needed to be animated

## Solution
Implementation of the animation for the scene

The scene first introduces a simple 4 state markov chain and displays an initial, customized and non-uniform distribution. First, some slow steps about how the simulation works are shown to follow the script. After some iterations, we proceed to iterate really fast in a timelapse-like motion reaching up to 100 iterations.

## Test
Animations run as expected. Here's a preview:

https://user-images.githubusercontent.com/50735312/166154273-3fd89c6c-0c95-42aa-8fd3-d169e198b624.mp4

### CODE REVIEW

**Comment by jesi-rgb** [comment]
drafting this while waiting for feedback! @nipunramk i'll probably need more revisions

**Comment by nipunramk** [comment]
@jesi-rgb great work, looks incredible!

Couple of minor suggestions:
1. Could we mathematically define D(pi_{n + 1}, pi_n) so users are clear that it's just a distance function (you can just use the L2 norm of the difference definition)
2. Could we also define a specific tolerance and say to continue until the distance meets the tolerance. Explicitly mention this in the animation and we could even have a checkmark light up when we are good. I think it would be a good addition to the scene.
3. Could we have the D() value be more significant figures so we can actually see changes? We can define the number of significant figures in relation to the tolerance we set. 

I think after those additions, we should be good to merge on this one!

**Comment by jesi-rgb** [comment]
@nipunramk Here's everyhing you told me added to the final scene! Feel free to suggest new changes or merge if you are happy with them!

You can modify the `tolerance` value within the code to make it take longer or shorter. Everything will follow accordingly!

https://user-images.githubusercontent.com/50735312/166671426-2b03a921-1da2-408b-ab54-02220c970f7d.mp4

**Comment by nipunramk** [comment]
@jesi-rgb  at 0:14, could we add a subscript of 2 to denote the L2 norm. So ||pi_n+1 - pi_n||_2 is perfect. Also, just curious the speed of the animations from 24 - 27 look incredible, I love how you did that. Was this all with the instant transition animations (and just reducing the runtime of it)? Seems to be that way in the code. I might steal that idea from you for some of my stuff as well :)

**Comment by jesi-rgb** [comment]
@nipunramk finished addressing all the feedback! I added the susbcript for the L2 norm, and also modified the last frame of the animation to indicate that this is the stationary distribution we were looking for. Here you have both the L2 norm change and the very last frame of the animation!

---

image


image

**Comment by nipunramk** [comment]
@jesi-rgb this looks good to merge but before merging, let me know the proper order to merge the pull requests.

**Pull request merged**
