### PR TITLE
Transition Other Approaches Scene

### PR DESCRIPTION
**Pull request by jesi-rgb**
# Scene
This scene tries to provide some useful, real-world context as to why the TSP problem is an important problem within the computer science research

# Video clip

https://user-images.githubusercontent.com/50735312/174753253-e27f5c75-80f9-460b-b10f-df71ada2cd10.mov

@nipunramk this one is the latest update to the video and I think I cannot make it any more random without it becoming absurdly jarring. Lemme know your thoughts! This is ready to merge

### CODE REVIEW

**Comment by jesi-rgb** [comment]
@nipunramk Lemme know your thoughts on this! it's a very early version of the first part for this section, but wanted to have early feedback just in case


https://user-images.githubusercontent.com/50735312/173708394-896312b3-e5a9-493c-9db8-c02a3a22e869.mp4

glorious 4K image here for reference:
usa-map-tsp

**Comment by nipunramk** [comment]
@jesi-rgb very cool, love the color of the nodes, and edges. Is it possible to try a different color scheme for the map? It looks a little too bright for my eyes (not dark mode friendly).  After that, we just need more nodes :)

**Comment by jesi-rgb** [comment]
yeah the app does not have dark mode support but i'll see what i can do!

also, how many nodes do you see in your head or more or less expect? there's 15 here if I recall correctly. lemme know since that also affects the map

**Comment by nipunramk** [comment]
@jesi-rgb well, the script says hundreds of thousands -- I was thinking it would be cool to have some like maybe 100-1000 central nodes and then many more smaller nodes as well to kind of make it look massive in scale.

Let me know if this is totally unreasonable and we can brainstorm further.

**Comment by jesi-rgb** [comment]
@nipunramk that sounds super cool, i'll try and come up with some method of doing that automatically!

**Comment by jesi-rgb** [comment]
@nipunramk surprisingly i got something very close to the thing! sorry for the absolute trash video quality, this one turned out being a bit bigger than usual so i had to reexport it!

Also, this video didn't take 3 years to render which is also very cool, so yeah lemme know your thoughts!

https://user-images.githubusercontent.com/50735312/174279091-4a706b6a-c13d-4615-aa7f-decc761aafbe.mov

**Comment by nipunramk** [comment]
@jesi-rgb very nice, let's add maybe a couple more central hub cities to it (Atlanta, Miami, Charlotte,  Seattle). Also maybe it would be interesting to have a bit more tour movement between the tours? Right now it seems like only 2-3 cities have their order changed up, which I think is fine, but occasionally, could we do bigger order changes to make things more dynamic? We may have to just experiment with it. We are very close though!

**Comment by nipunramk** [comment]
@jesi-rgb are you good to have this merged?

**Comment by jesi-rgb** [comment]
@nipunramk totally!

**Pull request merged**
