### PR TITLE
Problem Complexity Scene

### PR DESCRIPTION
**Pull request by jesi-rgb**
# Scene
Scene where we talk about some smarter strategies to approach the exact solution of the problem and show some context for the TSP in NP problems as well as a small complexity analysis.

# Video clip

https://user-images.githubusercontent.com/50735312/173610111-7b6256d5-f9c9-4984-8252-cb1e11d06f8c.mp4

### CODE REVIEW

**Comment by jesi-rgb** [comment]
@nipunramk another scene to check out!

Mind you, the first dynamic programming part of the video is not complete. I left that there for you to check out, which would be the first part of the algorithm (calculating every possible subproblem). It's lacking the last part in which you use the information to build the optimal path (I think it's lacking other things too... but mainly)

Wanted to get your thoughts on it since it's not as easy of an animation as I initially thought. If you believe it's worth, I'll finish it no problem, but it'll take a bit more time than I expected. 

If you ask me, I don't think it is a good enough animation to present and time should be spent more on other things such as annealing, ants or even christofides. The dynamic approach is not very good for animation in my opinion, or, at least, can't figure out a good enough animation in my head.

Lemme know your thoughts!!

**Comment by nipunramk** [comment]
@jesi-rgb I think what you have as of right now is good enough -- it does not need to be an exact animation of the DP approach with the exact, correct algorithm. We just need to show the basic idea and I think this accomplishes that. So don't think you need to work on it anymore. 

Other feedback:
0:29 - let's replace "complete coloring" with "subset sum" (I think it is a more clear example)
0:33 - I personally find it a little tricky to read/make out the O(1) and O(n) graphs because they are too dark. Generally I avoid putting text with that darker purple color -- let me know what you think would be a better choice for those colors.

**Comment by jesi-rgb** [comment]
great!! i'll fix the minor bugs that the DP animation has and that's it. 

i'll address everything else too! i'll see what colours should i choose for it to be better

**Comment by jesi-rgb** [comment]
New changes added! I chose to present the darker graphs in green as in "this is what we aspire to" and I think they are a bit more legible. Nevertheless, they are not the main character in that animation, but 2^n is, so that's why I don't worry too much about it

https://user-images.githubusercontent.com/50735312/174058257-2f7df028-dec2-4da6-baa2-453b88a1ad96.mp4

**Pull request merged**
