### PR TITLE
Changed styling of MarkovChainGraph

### PR DESCRIPTION
**Pull request by jesi-rgb**
-  Changed color of states (vertices)
-  Changed color and aspect of users
-  Changed font used in the states
-  Added `REDUCIBLE_MONO` and `REDUCIBLE_FONT` to `common/reducible_colors.py` file
-  Changed layout for users around their state to appear around the state with a poisson based distribution

### CODE REVIEW

**Comment by jesi-rgb** [comment]
This is how everything looks so far! White, mono font states with 50 users around it and labels indicating the probability that each edge has to be chosen.

dang

**Comment by nipunramk** [comment]
Looks really good, merging.

**Comment by jesi-rgb** [comment]
Currently working on something... let me know your thoughts! @nipunramk 

oof

**Comment by nipunramk** [comment]
@jesi-rgb yes, this is a great idea for handling current double ended arrows. One suggestion: can we have the tip of the arrow point to the outside of the state with a bit of buff instead of having the tip be in the center of the state. We can do the same for the starting point as well. I think that will make things look better.

**Comment by jesi-rgb** [comment]
@nipunramk the buff will stay for sure. Just... dealing with arrows is incredibly finicky 😭 but we are getting there!

**Comment by jesi-rgb** [comment]
After an exhaustingly long search, I finally found the answer to every problem so far!
aaaaa

**Pull request merged**
