### PR TITLE
RED-52: Develop tooling for convergence and RED-28: Periodicity Scene

### PR DESCRIPTION
**Pull request by nipunramk**
### Problem
Need tooling to demonstrate concept of convergence and change in distribution over time. Also need to use this in the Periodicity scene. 

### Solution
Added ability to configure states that have users of different colors (this helps with differentiating between states and corresponds with graph)
Generated a graph of line segments from the distribution sequence after a number of steps in the markov chain (note to do this without impacting simulation, did the transitions in a separate markov chain copy)
The line graph composed of line segments are rendered piece by piece along with the transitions of users. 

### Test
Scene renders well and markov chain changes made cause no regressions (only addition is logic for state_color_map for users). This is only conditionally enabled if markov chain passed such a map. 

https://user-images.githubusercontent.com/14256908/166642135-0d6f4c7f-70ff-4842-a99b-c81cb019b3ed.mp4

### CODE REVIEW

**Comment by nipunramk** [comment]
@jesi-rgb this scene is still a work in progress, but there were some tricky animations that were necessary to make it. Let me know if you have any feedback on ways to improve the look of it.

**Comment by jesi-rgb** [comment]
this LOOKS INSANE!! i will definitely think of ways to make this even cooler, but the graph is just so good!!

**Comment by nipunramk** [comment]
@jesi-rgb here are the animations for the Periodicity and IntroduceBigTheorem scenes.

Periodicity

https://user-images.githubusercontent.com/14256908/167094434-58ad1171-c17b-48b1-9ad0-7ac59bd5a9e2.mp4

IntroduceBigTheorem (here there are 4 scenes that I plan to edit together as a quad-screen picture in picture (each video plays simultaneously in a quarter of the screen) -- I think it will look super cool. Each scene is just a different initial distribution converging to a stationary distribution. 

https://user-images.githubusercontent.com/14256908/167094592-f1ec06bd-d216-42f1-966b-f4cc3632cf91.mp4


https://user-images.githubusercontent.com/14256908/167094610-49874adf-17b2-46cc-ae97-ea54a3cf042a.mp4


https://user-images.githubusercontent.com/14256908/167094614-8fdbe1b7-5b80-4dad-94be-41bdce7259ae.mp4


https://user-images.githubusercontent.com/14256908/167094620-d6f2f02a-7b89-4801-992d-f4ae310069ef.mp4

**Comment by jesi-rgb** [comment]
Great job! Lemme leave some super quick & easy suggestions:

## Periodicity
- at 1:35 we present this periodic markov chain. Would it be possible to move the first graph that appears to the center, and when the second one comes in, move it to its current position? Movements like this are interesting because they precede that something more important is going to happen, so you end up maybe missing the movement but not the important part. Anticipation!

## Big theorem
As for this scene, such a great job! Some things I'd suggest (this applies to every clip):
- The new node/graph colors that we eventually decide on (suggestion via text message)
- I need those numbers in the graph (1.0 and 25) to be defined; that is, **distribution** (or percentage, or whatever) and **iterations**. Labeling charts is very important!
- And I'd love for these chart numbers to appear in our lovely mono font, if it's not too much of a hassle.
- Super minor detail but could be cool is that, in very much the same fashion we are doing with other simulations, ramp the speed up towards the end. First 5 - 10 iterations are cool to watch, but after that, I get bored. I'd rather watch more iterations (50, for example) that run much faster. This will also help the graph to appear as it's being seamlessly drawn, rather than in chunks as it is now, which would be very nice.

Lemme know your thoughts!

**Comment by nipunramk** [comment]
@jesi-rgb here are the new animations after addressing all the feedback


https://user-images.githubusercontent.com/14256908/167240788-4a1a8e46-f8f6-408b-bdb7-d72d8e8d9561.mp4


https://user-images.githubusercontent.com/14256908/167240795-ad5381b4-90ad-4ec1-afdd-b57bb89f9585.mp4


https://user-images.githubusercontent.com/14256908/167240797-0932d47c-dbac-4435-976a-1a54be1d2530.mp4


https://user-images.githubusercontent.com/14256908/167240799-70d917d6-b3c1-48d0-8e84-dc53b57e458a.mp4


https://user-images.githubusercontent.com/14256908/167240800-a6378522-31d3-4a70-8928-c5185baf2c4a.mp4

**Pull request merged**
