### PR TITLE
RED-33: PerformanceEvaluation animation

### PR DESCRIPTION
**Pull request by jesi-rgb**
## Problem
`PerformanceEvaluation` needed animations!

## Solution

This PR proposes an animation for this scene, where a simulation takes place next to a little graph that shows how fast the convergence on the graph is achieved

## Video clip

https://user-images.githubusercontent.com/50735312/167450011-f027c5a2-de22-4fdf-b057-3413a158096e.mp4

### CODE REVIEW

**Comment by jesi-rgb** [comment]
@nipunramk this animation is currently running on your big network. Right now there are only 100 users, but we can add a lot more for the final scene.

As you did with your other animation, we can render this one in layers and merge them in post. This scene has all the users and the chain, and then you can render your chain. I think the markov chain should be the exact same, right? We seeded the np.random so it should appear the same in every system.

There are some things to polish. I'll see how I can fix the sudden stop when I rescale the graph. Have you got any other ideas about that? I tried LogScale, but it is completely bugged up.

**Comment by nipunramk** [comment]
Yes the Markov chain should be the same. Either way, I will have to locally render the scene anyways.  @jesi-rgb make sure you have some animations for the following sections:

"So, to take stock of where we are, we have a stationary distribution which is a good measure of the importance of every web page in a Markov chain. We now have three separate ways to calculate the stationary distribution. Here’s an interesting question for you:
 
Imagine we tried to find the stationary distribution of a massive web network of hundreds of millions of web pages, which for now, we’ll naively assume is modeled by an irreducible, aperiodic Markov chain. Which of these three methods do you think will perform best in practice?" 

Remember, when you are animating a scene, you should make sure each line of script has something that we can align with visually. The section after this works nicely with these animations, but we will need some more for the first part. The main part that needs to be added is small -- just some reference to the three methods and I can overlay them on top of the massive web network markov chain. 

Also, one thing I imagined is it would be funny to have some sort of comic/characters of some sort show up acting as an engineer and another as a mathematician, and then the engineer proposes the brute force solution and the mathematician is like "no way that beats the eigenvalue solution" or something like that. It's just nice to have something like that so the audience can get a change of pace and laugh. Perhaps brainstorm some funny and interesting way to incorporate this. I think it would be a good addition.

**Comment by nipunramk** [comment]
@jesi-rgb Also for the graph, could we be clear about what we are graphing? 
And modify the x and y axes as necessary between the two scalings so it's more clear. 

Two options to make it more smooth:
1. We can be fine with taking a gap to show the rescaling
2. Or we could just say you know, it's fine to just show one overall scale for the iterations and it's clear the convergence is still happening. 
Maybe option (2) is good enough? Let me know your thoughts on it

**Comment by jesi-rgb** [comment]
@nipunramk Will think about everything! 

Also, the labels on the scales are actually fixed, but didn't push them yet. And I think that option 2 will be the way to go. I wanted to show a little line that represented the tolerance value, but yeah don't think it adds much to the scene.

**Comment by jesi-rgb** [comment]
## Convergence scene (final frame)
Addressed the feedback!
PerformanceEvaluation_ManimCE_v0 15 2

## Big system of equations
I made a _small_ system with 50 equations. This takes an exhaustingly long time to render, let me know what you think.

https://user-images.githubusercontent.com/50735312/167730500-587c61fd-4b3a-48dc-bf0a-d67a78dd53bf.mp4

## Big eigen system
I imagine this playing and fading to black towards the end as we mention the eigen value methods.

https://user-images.githubusercontent.com/50735312/167730670-3fb18261-7fa1-4a8a-a4cf-010d08a6239e.mp4

## Intro PIP
This would hold the three previously shown scenes of the simulation, the systems and the eigenvalues.

PerformanceEvaluation_ManimCE_v0 15 2



@nipunramk lemme know your thoughts!

**Comment by nipunramk** [comment]
@jesi-rgb I like all the scenes, nicely done! Will look into merging tomorrow. I also changed the script a bit, so please do a double confirmation that every part of this section has some animations involved with it. I might also include some screencaps of some papers on it.

**Pull request merged**
