### PR TITLE
RED 97: Simulated Annealing Scene

### PR DESCRIPTION
**Pull request by jesi-rgb**
# Scene
Scene that shows an example and a simulation of how the Simulated Annealing heuristic works

# Video clip

https://user-images.githubusercontent.com/50735312/176646356-90795e4b-a695-4afb-8cd8-b8d13d138003.mp4

lemme know your thoughts, @nipunramk!

### CODE REVIEW

**Comment by nipunramk** [comment]
@jesi-rgb very nicely done. For the ending graph, when we don't accept the solution, it doesn't actually make sense to graph the increase in cost, right? We should only graph the increase in cost when we actually accept a worse solution. Otherwise, just graph that the cost stayed the same. I think once you modify the graph in that part as shown, it will be more clear. Also maybe for purposes of explanation, decay the temperature a little less drastically so people can see the increases in cost early on and then how afterwords, we basically never accept an increase in cost.

**Comment by jesi-rgb** [comment]
Here you can see the smoother change in Temp and some manual changes! Also, implemented the "Best" plot, in green, which shows the best solution's cost so far

@nipunramk 



https://user-images.githubusercontent.com/50735312/177147722-1e1b1ab0-a2b2-4f47-8298-77998d69601f.mp4

**Comment by jesi-rgb** [comment]
@nipunramk this should be ready to merge!

**Comment by nipunramk** [comment]
@jesi-rgb one more thing -- could we somehow label what the lines are plotting -- e.g I don't think anyone will know that the green line plots "best tour" and the purple line plots "explored tour"

**Pull request merged**
