### PR TITLE
RED-92: LowerBound Scene

### PR DESCRIPTION
**Pull request by nipunramk**
[Problem]
Need to create animations for Lower Bound explanations

[Solution]
Demonstrated concepts of MST's with Prim's algorithm. Then showed how they can be bounds of the TSP using the 1-tree concept.

[Test]
Scene renders as expected. 

https://user-images.githubusercontent.com/14256908/173769748-9478a976-efc4-4084-a589-9944ce96f3d4.mp4

### CODE REVIEW

**Comment by nipunramk** [comment]
@jesi-rgb I think I might reduce the opacity of the interconnecting edges between visited and unvisited sets, let me know if you have any further feedback.

**Comment by jesi-rgb** [comment]
@nipunramk yes, i'd do that! it probably is easier to read the graph, even more so if we have a particular path that we are building (marked in yellow in that case), so let that stand out a bit more.

### Some minor adjustments:

Make the modules here with bold font (for consistency):

image

---

These annotations are way too far down in the frame. I'd suggest scaling everything down by a tiny bit. Composition-wise is super good, but this far down will collide with youtube's play controls and I find that annoying. 

I'd also compensate by making the "Better lower bound" text bold, because that will have to be a bit smaller in order to find space for all the other things as I told you. It also very effectively gives the sensation of hierarchy of that being a title.

image


---
Separate the annotations a bit more from the graph since we now have tons more space:

image

**Comment by nipunramk** [comment]
@jesi-rgb incorporated the feedback suggestions. Will merge, let me know if you have any further feedback. 

https://user-images.githubusercontent.com/14256908/173996369-465aa576-e177-4932-99f1-ad890db02715.mp4

**Comment by jesi-rgb** [comment]
absolutely bonkers of an animation dude this video is really coming up nice

**Pull request merged**
