### PR TITLE
RED-96: Local Minima Scene

### PR DESCRIPTION
**Pull request by nipunramk**
[Problem]
Local Minima scene needs animations

[Solution]
Added heat map of search space with 2-opt improvement examples. Showed example of sub-optimal local search getting out of local minima.

[Test]
All scenes render as expected.

https://user-images.githubusercontent.com/14256908/176831416-4f6dd51a-5ad9-4c5b-b0d6-f90e9888ea08.mp4

### CODE REVIEW

**Comment by nipunramk** [comment]
@jesi-rgb take a look when you get the chance.

I was uncertain if we need arrows at all in the animation, so I put couple of examples of arrows showing 2-opt improvement, and then the final example has no arrows. Let me know what you prefer.

Another thought I had -- should we put some text for the cost of each cell so people know the actual cost values instead of kind of eyeballing it based on the color/configuration?

The text would only show up when we show the 2-opt neighbors (e.g at 0:10,  0:14, 0:18, etc).

**Comment by jesi-rgb** [comment]
fuck LOOKING AMAZING 🤩

**Comment by jesi-rgb** [comment]
If adding the cost is not very expensive (pun intended) then we can try out and see! At least only for the first ones to get a sense of how it'd look.

I don't know if I'm completely sold on the gradient squares on this one. I liked it a lot when the configs were "selected" like this:

image


but overall amazing job man!

**Comment by nipunramk** [comment]
@jesi-rgb can you clarify what you want changed about the gradient squares? 
Will also try adding cost and seeing what it does after I make some progress on Ant simulation!

**Pull request merged**
