### PR TITLE
RED-31: SystemOfEquationsMethod

### PR DESCRIPTION
**Pull request by jesi-rgb**
## Problem
`SystemOfEquationsMethod` needed to be animated!

## Solution
This PR proposes an animation to show how one would find the stationary distribution for a Markov Chain using a system of equations.

## Test
Here's the clip!

https://user-images.githubusercontent.com/50735312/166485525-66c70c61-9e30-447e-86a2-fa8e7887eec7.mp4

### CODE REVIEW

**Comment by nipunramk** [comment]
@jesi-rgb great work -- could we make some note at 0:10 that solving this system yields to infinitely many solutions? That part matches the script better and then we can replace one of the equations as you do.

**Comment by jesi-rgb** [comment]
@nipunramk you got it! i also made some minor adjustments. let me know what else should we change!

https://user-images.githubusercontent.com/50735312/166820142-ffd2e643-54f9-4759-8e0f-ea5e1cc79683.mp4

**Comment by nipunramk** [comment]
@jesi-rgb some more minor changes and we can merge:

At the very start, can we reference the definition of a stationary distribution, e.g pi = pi * P. That would match well with the first sentence in the script from the system of equations section. "The second way to solve for a stationary distribution is to utilize the definition of the stationary distribution directly. "

Maybe have the definition fade in, and then show the system of equations. 

And then at 0:05 in the script we say, "The trick to solving the system of equations is to add in the implicit constraint that the sum of individual probabilities of the final stationary distribution must equal 1." So can we add the constraint at the bottom with the system of equations, and then remove one equation and bring up the sum constraint?

**Comment by jesi-rgb** [comment]
@nipunramk You got it! This is how it's looking!

https://user-images.githubusercontent.com/50735312/166923900-4bdf86a3-9d79-4e48-8ab9-4ffd45350ea4.mp4

**Comment by nipunramk** [comment]
@jesi-rgb this looks good to merge but before merging, let me know the proper order to merge the pull requests. I see in the code that this also has BruteForce animations in there.

**Pull request merged**
